// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TokenByCredentialsOKCode is the HTTP code returned for type TokenByCredentialsOK
const TokenByCredentialsOKCode int = 200

/*TokenByCredentialsOK token by credentials o k

swagger:response tokenByCredentialsOK
*/
type TokenByCredentialsOK struct {

	/*
	  In: Body
	*/
	Payload *TokenByCredentialsOKBody `json:"body,omitempty"`
}

// NewTokenByCredentialsOK creates TokenByCredentialsOK with default headers values
func NewTokenByCredentialsOK() *TokenByCredentialsOK {

	return &TokenByCredentialsOK{}
}

// WithPayload adds the payload to the token by credentials o k response
func (o *TokenByCredentialsOK) WithPayload(payload *TokenByCredentialsOKBody) *TokenByCredentialsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the token by credentials o k response
func (o *TokenByCredentialsOK) SetPayload(payload *TokenByCredentialsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TokenByCredentialsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
